### ISSUE TITLE
error on installing, mac OS

### ISSUE THREAD

**Issue by tob-har** [GrandaddyShmax/audiocraft_plus#15]
Cannot install on MacOS due to that problem:

ImportError: dlopen(/Users/XXXXX/opt/anaconda3/lib/python3.9/site-packages/taglib.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace (__ZN6TagLib10StringList6appendERKNS_6StringE)

Any idea on how to fix it? Thanks for your support!

mac os 12.6.5
M1

**Comment by GrandaddyShmax** [comment]
Sadly I myself have no way to check your issue, i do not own any device with mac os..
Searching your error, it is something related to taglib library. Can you check if the TagLib was installed properly and what version is it?

**Comment by tob-har** [comment]
thanks for getting back!
i cloned the repo, torch was already installed, then used `pip install -e .`
seems like an error caused by taglib. I installed taglib v 1.13.1 using brew, and it suceeded. Using python 3.9.
Error is not resolved.

Someone sucessfully installed on Mac OS 12.6 M1?

**Comment by GrandaddyShmax** [comment]
If it'll help I can make a sort of mitigation for Mac os by disabling taglib and everything that depends on it. However this will break the functionality of storing metadata in your generations

**Comment by tob-har** [comment]
this sounds like a great quick fix! Appreciate your support! For the first run, this downside would be ok. I will continue investigate on the taglib issue on mac on my side and post if I find a solution. Thank you!

**Comment by GrandaddyShmax** [comment]
I have uploaded a new version temporarily under the branch of `mac-os-fix`, check if it works for you and I will merge it into the main branch

**Comment by tob-har** [comment]
Thank you!
tested, unfortunately the same issue:

Successfully installed audiocraft-0.0.2a2
(base) XXXXX audiocraft_plus-mac-os-fix % python app.py
Traceback (most recent call last):
  File "/Users/XXXXXX/Documents/audiocraft_plus-mac-os-fix/app.py", line 29, in <module>
    import taglib
ImportError: dlopen(/Users/XXXXXXXX/opt/anaconda3/lib/python3.9/site-packages/taglib.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace (__ZN6TagLib10StringList6appendERKNS_6StringE)

in the app.py file, there is also the 'import taglib' still implemented in line 29.

just tried the original audiocraft version, this runs, but what the gradio interface offers is way to limited, eg. no .wav export :)

**Comment by tob-har** [comment]
is this a suitable version?

v2.0.0
https://github.com/supermihi/pytaglib

there is one breaking change announced for that version: 
"breaking change: File.path is now a Path object"
see: https://pypi.org/project/pytaglib/

**Comment by GrandaddyShmax** [comment]
> is this a suitable version?
> 
> v2.0.0 https://github.com/supermihi/pytaglib
> 
> there is one breaking change announced for that version: "breaking change: File.path is now a Path object" see: https://pypi.org/project/pytaglib/

Does that version work for you?

**Comment by GrandaddyShmax** [comment]
> yes, it is working fine in general. but with this version installed, the audiocraft_pluss app is giving that error mentioned above. Sorry, I am not an expert in that field. If you can give me hints, what exactly I could test for you, please let me know.
> 
> btw.: studying your py script "app.py" helped me a lot of understanding general topics in that field. appreciate your work and effort!

I have updated the mac-os-fix branch, tell me if this time it works. I changed the version to be 2.0.0 for taglib

**Comment by tob-har** [comment]
cmd refers to the mac terminal.

I built taglib / pytaglib from scratch for my system, works.
But still, the error is not resolved. I also tried a dedicated virtual env but also not succeeding.

**Comment by GrandaddyShmax** [comment]
> cmd refers to the mac terminal.
> 
> I built taglib / pytaglib from scratch for my system, works. But still, the error is not resolved. I also tried a dedicated virtual env but also not succeeding.

did you run the terminal inside the audiocraft_plus folder?

**Comment by tob-har** [comment]
yes...

**Comment by GrandaddyShmax** [comment]
In that case ill just make a separate branch supporting only mac. I updated the `mac-os-fix` branch once again, this time removing entirely taglib and all it's dependencies, check if it works for you

**Comment by tob-har** [comment]
Great! Works perfectly well. Thank you!

I just had to out comment/delete lines 405 and 406 of your code:
```
#torch.cuda.empty_cache()
#torch.cuda.ipc_collect()
```
as the mac runs the process on CPU and trying to call the functions above crashes the process at that moment.

**Comment by GrandaddyShmax** [comment]
> Great! Works perfectly well. Thank you!
> 
> I just had to out comment/delete lines 405 and 406 of your code:
> 
> ```
> #torch.cuda.empty_cache()
> #torch.cuda.ipc_collect()
> ```
> 
> as the mac runs the process on CPU and trying to call the functions above crashes the process at that moment.

ill update the branch so that the future updates will not enable them again 👍

**Comment by tob-har** [comment]
Great! Thank you for your work!!!
