### ISSUE TITLE
Longer durations cause error

### ISSUE THREAD

**Issue by Drommer-Kille** [GrandaddyShmax/audiocraft_plus#16]
Up to 60sec this works fine, but 120sec cause error. Original audiocraft generates 120sec files just fine so it's not hw related. GPU is RTX3090 with 24gb VRAM.

This error after it gets to the 1500 steps: TypeError: MusicGen.generate_continuation() got an unexpected keyword argument 'melody_wavs'

**Comment by GrandaddyShmax** [comment]
That is strange, Using the colab with T4 GPU with 16GB I managed to generate up to 200sec
Can you check if you are hitting the cap when generating 120sec? how much VRAM is used?

**Comment by Drommer-Kille** [comment]
VRAM is 14/24gb during and jumps to 15,7/24gb when the error comes. So it's not running out of memory.
launch.py", line 156, in predict
    next_segment = MODEL.generate_continuation(last_chunk,
TypeError: MusicGen.generate_continuation() got an unexpected keyword argument 'melody_wavs'

The bigger problem is that, this is not the same model as the original Audiocraft. At least it produces totally different results. This does not seem to follow the prompt at all.

That said, my gradio gui looks different than the plus screenshot. I have seed etc, but not the several prompt boxes.

**Comment by GrandaddyShmax** [comment]
Can you screenshot the gui that you currently have?

**Comment by Drommer-Kille** [comment]
Here
![Screenshot (65)](https://github.com/GrandaddyShmax/audiocraft_plus/assets/123734699/f7a9262d-f774-4f45-8761-b9a85bc19783)

**Comment by GrandaddyShmax** [comment]
It seems like you somehow cloned a very early version of this repo, try to do a git pull

**Comment by Drommer-Kille** [comment]
Git pull: Already up to date.

**Comment by GrandaddyShmax** [comment]
Are you perhaps running the launch.py?

**Comment by Drommer-Kille** [comment]
User error, sorry for wasting time :(
Using app.py it launches the correct version and i have generated 240sec audiofile without any problem. Since it can batch prompts it would also be nice to be able to run single prompt multiple times to separate files without overlap. Or all prompts to separate files without overlap.

Huge thanks for creating this!

**Comment by Drommer-Kille** [comment]
Any idea why it did that? I'm asking as i'm now testing the new release of Audiocraft with MultiBand Diffusion and i get the same error if trying to generate longer files than 60sec. I can generate 5min clips with audiocraft+ but the official repo gives cuda memory error for 120sec files. 
Any plans on supporting MultiBand Diffusion on + version?

Not that it's much better: Dataset is still same 16khz mono and MBD tries to restore some high frequencies while adding weird artifacts to the sound. Not a big improvement. But the training sound interesting if that could be done with 44.1kHz files.

**Comment by GrandaddyShmax** [comment]
working on implementing the new update, from my testing so far the multiband requires much more VRAM.

**Comment by Drommer-Kille** [comment]
That seems to be the case, With MB disabled it generates 120sec clips. Any plans on integrating the training code to +?

**Comment by GrandaddyShmax** [comment]
I'll try, cannot promise though of success
