### ISSUE TITLE
Collab support discontinued?

### ISSUE THREAD

**Issue by pramatias** [GrandaddyShmax/audiocraft_plus#30]
Hello, the google collab opens the audiocraft+ 2.0.0a gradio, but upon running it, throws an error. Observing that the README doesn't mention any collab version anymore, does the 2 version dropped support?

**Comment by pramatias** [comment]
By running a lot of collabs in camenduru's page, as well as the version of colab in audiocraft_plus Musicgen.md, they all fail with the same error [1]. So i guess the right place to file the issue, is camenduru's github project. 

If i may ask, Musicgen's page in audiocraft_plus, it doesn't redirect to audiocraft_plus 2.0.0a version, but rather to a very primitive version of the colab. That's what i meant in the original question, won't future versions of audiocraft_plus support the colab? 

[1] ImportError: /usr/local/lib/python3.10/dist-packages/lameenc.cpython-310-x86_64-linux-gnu.so: undefined symbol: __pow_finite

**Comment by GrandaddyShmax** [comment]
not sure i understood your question but if you are looking for a colab here it is: https://colab.research.google.com/github/camenduru/MusicGen-colab/blob/main/MusicGen_ClownOfMadness_plus_colab.ipynb
should be working fine

**Comment by pramatias** [comment]
Thanks @GrandaddyShmax it works fine. Much appreciated. 

Other versions of the colab did throw some errors, all the same error btw. The colab version i was running was the one audiocraft_plus had in it's README, in which the colab link is not there anymore. I thought maybe it was deprecated or something. 

Anyway, issue resolved. Cheers!
