### ISSUE TITLE
Web ui not displaying the generated audio wav and mp4.

### ISSUE THREAD

**Issue by pramatias** [GrandaddyShmax/audiocraft_plus#4]
The web ui, sometimes hangs, and it displays error, in the audio and the mp4 section. The console however points out, that the files are generated. 

Is there a way to find, and download the files from the files folders? I searched all around, i couldn't figure out where the files are temporary located, in the file hierarchy.

**Comment by GrandaddyShmax** [comment]
all the generated files should appear in the main folder. if you are using a colab, there is a chance that it just disconnected.
Does the issue remain after restarting the colab?

**Comment by pramatias** [comment]
Yes in the collab version. The next time i try to generate, it generates the song without a problem, with not even restarting. 

But when it displays an error, the console of the collab writes that the song (and video) was generated correctly after finishing the batch. So could it be, that the files are somewhere, but the webui has a bug sometimes?

The reason i want to retrieve the files, song and video, is that some executions take a long time to complete, like 10 - 15 minutes, but if it finishes execution and the files are somewhere, i can search and download them manually from there. 

Maybe it is an encoder issue, and the batch finished, but it fails to produce the video? Also the free collab accounts have a history of stalling i think, maybe that is.

I have not the console output on hand, but it displays that batch finished, generated video and sound, something like that.  So i was wondering, the produced files wav & mp4, in the file hierarchy, are they located somewhere? Like audiocraft/...

**Comment by GrandaddyShmax** [comment]
so far i don't seem to get the error that you receive but regardless you can find the generated audio here:
![image](https://github.com/GrandaddyShmax/audiocraft_plus/assets/52707645/c40c698f-1b9d-44f8-a88b-bb879221fbc7)

**Comment by pramatias** [comment]
That's the location i was looking for. Thanks @GrandaddyShmax. 

The error happens rarely, once every 10 or 20 runs, especially when there is some long computation, of 10 min or more. It happens in short computations as well. If the file is generated, and the webui displays an error, then it must be a webui bug. If the file is not generated it must be an error in the collab. 

The next time i put it to generate, it generates without a problem. I don't restart anything, i just press the generate button again and everything goes smoothly.

**Comment by pramatias** [comment]
In the end, the problem is in the webui. All 3 windows of generation, video, audio and progress, display a red "error" but the batch in the console continues, and after a while the video-audio are generated correctly, and can be downloaded from the files section. 

So that's fine with me, no problem, in the next computation without even restarting anything the webui and console work normally.

The error happens randomly, this time it happened in 89% progress of the song.

**Comment by GrandaddyShmax** [comment]
Not exactly, the problem comes from the colab itself, not specifically mine. if you try any other colab, you'll have similar experience with random disconnection errors. it mostly depends on the internet connection between you and the colab servers. Not something that i can truly do to mitigate this issue

**Comment by pramatias** [comment]
No problem @GrandaddyShmax ,thanks for the help. I just described the problem and the workaround, for anyone else who might face the same issues. Cheers!
