### ISSUE TITLE
Bug in temperature settings

### ISSUE THREAD

**Issue by pramatias** [GrandaddyShmax/audiocraft_plus#5]
Isn't the temperature supposed to be, a float between 0 and 1? The UI permits higher values, as well as the numbers with every click, go up by one, instead of a 0.1 or something like that.

If i may suggest, the way the GPT's temperature is defined, is a slider of 0 until it reaches 1. The same javascirpt element we define seconds of the song, in the audiocraft UI. 

Apart from that the UI, is very easy and a joy to to use it. Thanks!

**Comment by GrandaddyShmax** [comment]
while it is true regarding the GPT that they set the limit to be between 0 to 1, that is not a hard limit. not an expert in this field but I know for example that many open-sourced LLM's run better with temperature higher than 1.

But speaking of Musicgen, the author only set the limit for temperature to not go below 0.

**Comment by pramatias** [comment]
Ok, no problem. The article here, regarding temperature, doesn't mention min and max values either. In my experience using MusicGen temperature dialed up to 1, seems very random, judging from the results. But i don't know the answer neither.  

 https://github.com/FurkanGozukara/Stable-Diffusion/blob/main/Tutorials/AI-Music-Generation-Audiocraft-Tutorial.md
